Use a connection per fork in preprocess
This patch resets the global session maker from, since `libpq` connection have
problems with running on forks, see
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT and

So every worker in the multiprocessing pool does have its own database
connection.

This fixes the

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: decryption failed or bad record mac`
```

Tracebacks during the import.